Proceso TRUCOOOOO
	Definir TotalCpj1, TotalCpj2, TotalCpj3, TotalCpj4, TotalCpj5, TotalCpj6, premioRepartir, parteCadaPJ, MitadPremio, PartePorPtsCPJ1, PtsTotal, PartePorPtsCPJ2, PartePorPtsCPJ3, PartePorPtsCPJ4, PartePorPtsCPJ5, PartePorPtsCPJ6 Como Real;
	Definir PtsPj1, PtsPj2, PtsPj3, PtsPj4, PtsPj5, PtsPj6 Como Entero;
	Escribir 'ingrese valor de premio a repartir';
	Leer premioRepartir;
	Escribir 'ingrese puntos de jugador 1';
	Leer PtsPj1;
	Escribir 'ingrese puntos de jugador 2';
	Leer PtsPj2;
	Escribir 'ingrse puntos de jugador 3';
	Leer PtsPj3;
	Escribir 'ingrese puntos de jugador 4';
	Leer PtsPj4;
	Escribir 'ingrese puntos de jugador 5';
	Leer PtsPj5;
	Escribir 'ingrese puntos de jugador 6';
	Leer PtsPj6;
	MitadPremio <- premioRepartir*0.5;
	PtsTotal <- PtsPj1+PtsPj2+PtsPj3+PtsPj4+PtsPj5+PtsPj6;
	parteCadaPJ <- MitadPremio/6;
	PartePorPtsCPJ1 <- (PtsPj1/PtsTotal)*MitadPremio;
	PartePorPtsCPJ2 <- (PtsPj2/PtsTotal)*MitadPremio;
	PartePorPtsCPJ3 <- (PtsPj3/PtsTotal)*MitadPremio;
	PartePorPtsCPJ4 <- (PtsPj4/PtsTotal)*MitadPremio;
	PartePorPtsCPJ5 <- (PtsPj5/PtsTotal)*MitadPremio;
	PartePorPtsCPJ6 <- (PtsPj6/PtsTotal)*MitadPremio;
	TotalCpj1 <- parteCadaPJ+PartePorPtsCPJ1;
	TotalCpj2 <- parteCadaPJ+PartePorPtsCPJ2;
	TotalCpj3 <- parteCadaPJ+PartePorPtsCPJ3;
	TotalCpj4 <- parteCadaPJ+PartePorPtsCPJ4;
	TotalCpj5 <- parteCadaPJ+PartePorPtsCPJ5;
	TotalCpj6 <- parteCadaPJ+PartePorPtsCPJ6;
	Escribir 'el premio para el jugador 1 es de', TotalCpj1;
	Escribir 'el premio para el jugador 2 es de', TotalCpj2;
	Escribir 'el premio para el jugador 3 es de', TotalCpj3;
	Escribir 'el premio para el jugador 4 es de', TotalCpj4;
	Escribir 'el premio para el jugador 5 es de', TotalCpj5;
	Escribir 'el premio para el jugador 6 es de', TotalCpj6;
FinProceso
